from copy import deepcopy


def list_worlds() -> list[str]:
    """Return a list of all available world preset names."""
    return list(WORLD_PRESETS.keys())


def evolve_world(base: str, changes: dict) -> dict:
    world = deepcopy(WORLD_PRESETS[base])
    world.update(changes)
    return world


def describe_world(name: str) -> str:
    """Return a human-readable description of a world preset."""
    try:
        preset = WORLD_PRESETS[name]
    except KeyError:
        raise ValueError(f"Unknown world preset: {name}")  # noqa: B904
    return f"{preset['name']}: {preset['description']}"


def load_world(name: str = "default") -> dict:
    if name not in WORLD_PRESETS:
        print(f"[WARN] Unknown world '{name}', falling back to 'default'.")
        name = "default"
    return deepcopy(WORLD_PRESETS[name])


def add_mutant_worlds():
    """Add mutant world presets with extreme mutation rates."""
    mutant = evolve_world(
        "garden_world",
        {
            "mutation_rate": 0.5,
            "mutation_strength": 0.1,
            "event_chance": 0.05,
            "disaster_chance": 0.02,
            "disaster_impact": 0.1,
        },
    )
    chaotic_mutant = evolve_world(
        "chaotic_world",
        {
            "mutation_rate": 0.7,
            "mutation_strength": 0.2,
            "event_chance": 0.2,
            "disaster_chance": 0.15,
            "disaster_impact": 0.5,
        },
    )
    WORLD_PRESETS["mutant_garden_world"] = mutant
    WORLD_PRESETS["mutant_chaotic_world"] = chaotic_mutant  # More extreme chaos


WORLD_PRESETS = {
    "default": {
        "name": "default",
        "description": "Balanced simulation with moderate conditions and average dynamics.",
        "resource_availability": 1.0,
        "temperature": 25.0,
        "pollution": 0.1,
        "event_chance": 0.03,
        "interaction_strength": 0.5,
        "mutation_rate": 0.1,
        "mutation_strength": 0.01,
        "predator_chance": 0.1,
        "predator_threshold": 350,
        "predator_impact_percentage": 0.13,
        "resource_regeneration_rate": 0.5,
        "seasonal_variation": 0.2,
        "catastrophe_threshold": 0.0,
        "radiation_background": 0.1,
        "disaster_chance": 0.1,
        "disaster_impact": 0.1,
        "growth_rate": 1.0,
        "death_rate": 1.15,
        "competition_intensity": 0.5,
        "carrying_capacity": 2500,
        "prosperity_threshold": 200,
        "prosperity_boost": 1,
        "optimal_density": 1000,
        "density_efficiency": 0.2,
    },
    "harsh_world": {
        "name": "harsh_world",
        "description": "A brutal environment with scarce resources and frequent threats.",
        "resource_availability": 0.4,
        "temperature": 5.0,
        "pollution": 0.6,
        "event_chance": 0.08,
        "interaction_strength": 0.8,
        "mutation_rate": 0.2,
        "mutation_strength": 0.05,
        "predator_chance": 0.25,
        "predator_threshold": 150,
        "predator_impact_percentage": 0.25,
        "resource_regeneration_rate": 0.2,
        "seasonal_variation": 0.6,
        "catastrophe_threshold": 500,
        "radiation_background": 0.2,
        "disaster_chance": 0.05,
        "disaster_impact": 0.4,
        "growth_rate": 0.8,
        "death_rate": 1.4,
        "competition_intensity": 0.9,
        "carrying_capacity": 300,
        "prosperity_threshold": 200,
        "prosperity_boost": 1.3,
        "optimal_density": 600,
        "density_efficiency": 0.2,
    },
    "garden_world": {
        "name": "garden_world",
        "description": "A utopian paradise with abundant resources and minimal dangers.",
        "resource_availability": 1.3,
        "temperature": 22.0,
        "pollution": 0.01,
        "event_chance": 0.01,
        "interaction_strength": 0.3,
        "mutation_rate": 0.05,
        "mutation_strength": 0.02,
        "predator_chance": 0.03,
        "predator_threshold": 600,
        "predator_impact_percentage": 0.03,
        "resource_regeneration_rate": 0.9,
        "seasonal_variation": 0.1,
        "catastrophe_threshold": 0.3,
        "radiation_background": 0.01,
        "disaster_chance": 0.1,
        "disaster_impact": 0.1,
        "growth_rate": 1.3,
        "death_rate": 0.95,
        "competition_intensity": 0.2,
        "carrying_capacity": 2000,
        "prosperity_threshold": 200,
        "prosperity_boost": 1.35,
        "optimal_density": 900,
        "density_efficiency": 0.35,
    },
    "chaotic_world": {
        "name": "chaotic_world",
        "description": "Volatile and unpredictable environment with frequent disasters and mutations.",
        "resource_availability": 0.9,
        "temperature": 30.0,
        "pollution": 0.3,
        "event_chance": 0.15,
        "interaction_strength": 0.7,
        "mutation_rate": 0.3,
        "mutation_strength": 0.1,
        "predator_chance": 0.3,
        "predator_threshold": 200,
        "predator_impact_percentage": 0.25,
        "resource_regeneration_rate": 0.4,
        "seasonal_variation": 0.8,
        "catastrophe_threshold": 300,
        "radiation_background": 0.2,
        "disaster_chance": 0.1,
        "disaster_impact": 0.6,
        "growth_rate": 1.0,
        "death_rate": 1.2,
        "competition_intensity": 0.8,
        "carrying_capacity": 500,
        "prosperity_threshold": 200,
        "prosperity_boost": 1.3,
        "optimal_density": 600,
        "density_efficiency": 0.2,
    },
    "dunbars_world": {
        "name": "dunbars_world",
        "description": "Cooperation thrives in small groups, but growth beyond ~200 causes rapid collapse.",
        "resource_availability": 0.9,
        "resource_regeneration_rate": 0.7,
        "temperature": 20.0,
        "pollution": 0.05,
        "seasonal_variation": 0.1,
        "mutation_rate": 0.07,
        "interaction_strength": 0.3,
        "mutation_strength": 0.02,
        "radiation_background": 0.05,
        "event_chance": 0.04,
        "disaster_chance": 0.03,
        "disaster_impact": 0.2,
        "catastrophe_threshold": 300,
        "predator_chance": 0.1,
        "predator_threshold": 220,
        "predator_impact_percentage": 0.15,
        "growth_rate": 0.9,
        "death_rate": 1.0,
        "competition_intensity": 0.7,
        "carrying_capacity": 300,
        "prosperity_threshold": 80,
        "prosperity_boost": 1.4,
        "optimal_density": 150,
        "density_efficiency": 0.35,
    },
    "post_cataclysmic_world": {
        "name": "post_cataclysmic_world",
        "description": "Life clings on after mass extinction — low resources, slow recovery, but huge evolutionary leaps.",
        "resource_availability": 0.3,
        "resource_regeneration_rate": 0.2,
        "temperature": 10.0,
        "pollution": 0.5,
        "seasonal_variation": 0.3,
        "mutation_rate": 0.25,
        "mutation_strength": 0.06,
        "radiation_background": 0.4,
        "event_chance": 0.02,
        "disaster_chance": 0.05,
        "disaster_impact": 0.6,
        "catastrophe_threshold": 0.0,
        "predator_chance": 0.05,
        "predator_threshold": 100,
        "predator_impact_percentage": 0.1,
        "growth_rate": 0.6,
        "death_rate": 1.1,
        "competition_intensity": 0.4,
        "carrying_capacity": 500,
        "prosperity_threshold": 50,
        "prosperity_boost": 1.6,
        "optimal_density": 200,
        "density_efficiency": 0.25,
    },
    "runaway_evolution_world": {
        "name": "runaway_evolution_world",
        "description": "Extreme radiation and mutation pressure drive rapid, chaotic evolutionary leaps.",
        "resource_availability": 1.0,
        "resource_regeneration_rate": 0.6,
        "temperature": 35.0,
        "pollution": 0.2,
        "seasonal_variation": 0.5,
        "mutation_rate": 0.6,
        "mutation_strength": 0.15,
        "radiation_background": 0.8,
        "event_chance": 0.08,
        "disaster_chance": 0.1,
        "disaster_impact": 0.4,
        "catastrophe_threshold": 800,
        "predator_chance": 0.2,
        "predator_threshold": 500,
        "predator_impact_percentage": 0.2,
        "growth_rate": 1.2,
        "death_rate": 1.3,
        "competition_intensity": 0.8,
        "carrying_capacity": 1500,
        "prosperity_threshold": 300,
        "prosperity_boost": 1.2,
        "optimal_density": 800,
        "density_efficiency": 0.15,
    },
    "red_queen_world": {
        "name": "red_queen_world",
        "description": "Intense competition and constant adaptation — evolve or die in an endless arms race.",
        "resource_availability": 0.7,
        "resource_regeneration_rate": 0.5,
        "temperature": 28.0,
        "pollution": 0.25,
        "seasonal_variation": 0.4,
        "mutation_rate": 0.35,
        "mutation_strength": 0.08,
        "interaction_strength": 0.75,
        "radiation_background": 0.2,
        "event_chance": 0.12,
        "disaster_chance": 0.07,
        "disaster_impact": 0.3,
        "catastrophe_threshold": 400,
        "predator_chance": 0.25,
        "predator_threshold": 250,
        "predator_impact_percentage": 0.2,
        "growth_rate": 1.0,
        "death_rate": 1.3,
        "competition_intensity": 1.0,
        "carrying_capacity": 800,
        "prosperity_threshold": 150,
        "prosperity_boost": 1.25,
        "optimal_density": 400,
        "density_efficiency": 0.25,
    },
}
